### PR TITLE
Operators |= and ^= implemented

### LINKED ISSUE #70: Add |= and ^= operator tokens (use &= as a reference)
### TODO:
Currently, we're missing the `&=` `|=` and `^=` tokens, and using them causes a compile-time error.
The expression `a &= b` will be compiled as `a = a & b` and we already have the functionality for that. Adding the tokens for the operators is sufficient.

### How to implement
- I've made a walkthrough on how to do it in #69 use it for a reference.
- see it's [`diff`](https://github.com/ThakeeNathees/pocketlang/pull/69/files) and complete the todos

### Finally
Don't forget to add some tests (at basics.pk).

### PR DESCRIPTION
**Pull request by alexcpatel**
*Edit Resolves: #70*

### CODE REVIEW

**Review by ThakeeNathees — APPROVED** [review]

**Comment by ThakeeNathees** [comment]
Thanks!

And you're more than welcome here to collaborate with us, as we're trying to learn the compiler concepts by making one. I'll create these "good first issues" more if you're interested.

**Comment by alexcpatel** [comment]
Thanks for marking this with "good first issue"! This is the first I've contributed to a project out of work/school :)

Would definitely be interested in contributing more. I'd love to learn more about compilers.

Also I noticed that the `~` operator doesn't work? Didn't really dive deep into the code past your example for `&=`, but trying to use it in a test case gave an undefined op error.
Additionally I encountered an error in `compilerChangeStack` when running some of the tests.
Maybe there could be a "testing" section to the README? Not sure what python version to use, and I had to replace the 'pocket' command with '../build/debug/pocket'.

Thanks!

**Comment by ThakeeNathees** [comment]
Thanks for reporting the issue, It's an assertion failure I've added after #67, and it'll fix it by today. but If you encounter a crash with a TODO: message (like this bellow) it's something that hasn't implemented yet.
```
>>> ~1
Assertion failed: TODO: It hasn't implemented yet.
        at runFiber() (C:\dev\pocketlang\src\pk_vm.c:1220)
```
Open an issue reporting these assertions, or if you want to implement it by yourself, I can help you on the issue thread. The source code heavily [commented](https://github.com/ThakeeNathees/pocketlang/blob/49c1fec85f04f4f531df170b58508b287e5c511a/src/pk_vm.c#L500-L517) for [readability](https://github.com/ThakeeNathees/pocketlang/blob/49c1fec85f04f4f531df170b58508b287e5c511a/src/pk_vm.h#L131-L170) and feel free to ask me if you have trouble understanding the internals.
@alexcpatel

**Comment by alexcpatel** [comment]
@ThakeeNathees awesome, thanks!

**Pull request merged**
