### PR TITLE
Log and Round Functions

### PR DESCRIPTION
**Pull request by naurelius**
Just decided to tinker a bit, I added the log10 and round functions to the math module

### CODE REVIEW

**Review by ThakeeNathees — APPROVED** [review]
I really was thinking about opening a "good first issue" to add more math functions.

Thank you for taking your time and effort to make this PR, and we're glad to have you here 🎉

**Comment by xSavitar** [comment]
Would have been good if this was shipped with test cases. But a follow-up with it is not a bad idea :)

**Comment by ThakeeNathees** [comment]
@xSavitar I've added some tests myself just after I've merged it. @victorakpan-dev Just a reminder for next time, write some tests for the implementations.

https://github.com/ThakeeNathees/pocketlang/blob/6ad5dfe9f7a02bbd837f3bae784d66b503b0616d/tests/lang/core.pk#L82-L85

**Comment by xSavitar** [comment]
Awesome!

**Comment by naurelius** [comment]
@ThakeeNathees Thanks for the reminder. Will do next time

**Pull request merged**
