### PR TITLE
doc: add a better phrase to credit wren

### LINKED ISSUE #145: A better phrase to credit Wren
> The language is written using Wren Language and their wonderful book Crafting Interpreters as a reference.

The phrase in the readme (above) seems to confuse several people into think that pocket is written in [Wren](https://wren.io/). But it's written in pure C99.

**We need a better phrase to clarify this and credit wren.**

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #145
Hi @ThakeeNathees, how does this look?
Let me know if this needs any changes.
Thanks

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
@RhnSharma and @ThakeeNathees what about something with inspired?

"Inspired by Wren and its wonderful book"

**Comment by tsujp** [comment]
The language is inspired by Ruby and Python, not Wren in the most literal sense of the word. As this PR is worded I think it's fine (and most clear).

**Comment by TiagoCavalcante** [comment]
It is inspired in the syntax of Python and Ruby and in the implementation of Wren. Anyway I guess this is a big improvement.

**Review by ThakeeNathees — APPROVED** [review]
@tsujp I too think it's fine. As @TiagoCavalcanteTrindade said, the syntax is inspired by ruby and python, and the implementation 
and the performance is inspired by wren.

And @RhnSharma, Thanks for your first contribution, we're glad you're here 🎉

**Pull request merged**
